# Generated by Django 4.1.4 on 2023-06-26 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0073_daily_leeds_exists_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 26)),
        ),
    ]
