# Generated by Django 4.1.7 on 2023-06-27 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0075_alter_daily_leeds_exists_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 27)),
        ),
    ]
